---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "XWAAQ/YpN5s6xZknnRZKnkcUy5GkbI6nxGjZYOH+ZmYUEg+EnWzliwYmZ4zOzOtmQUTx7X6UMHfxb4Z7uyPA0z/mjVnIRCoqv6QAmbTHJBztzjyJy3HpDvX7IYO6Lrr+T0RHQ5uGarpXsUxCrCD+fKf1WfyVy/XJ8Uw1gPY7fEpjB+xRtxwYukRmZFxjcUnbBwguVSveoUBhyn6vr+cW4rovtB5s443H5UXQeprSY0Pu28G77rnc2opk1CLP0P/gwetPjnFaZRwYY0L0VNER877sloZ8IcY47ThdBNVpkkMbpJgkSQW7brSIjefP1S9kx00b6XqwV/8zh/DSi2j8mq8CU2g2qLm8M5F/ik1d/sc23wxCnj+GWeBoAlPcpgCYM8nYp8oS09H32TQFG7iENu3nG+9YsoNKdUSPQvfqYkXtO7Sbtvjgiv0rhhZJLsvqnrh2Dq/6Y2K1jmDcZuQfFDgdCTW85zLDle78zFyiIjLc41QX4Rqo9ELJNR5KQ60pQIoIb/JxRvEERvzOBJl+atAa4CvI+UdU/xUFEokWXLwGi+Ze+cu7Qfskg6ISCzGAZ/D1aJ0R8wHjwY/BdiM0oSadlGl13yU1jVSWoHwpnmpBZIuGnPrCGPf3VLzRGPdkAej+RCdt4DKCNUb8BZ67f4nP3gwAEBYbOle58O4tA2c="
  email: false
