---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos" tag="7"
    - image="redhat" tag="7"
    - image="centos"
    - image="redhat"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "bPMYgxeg7GNaRQnvYIeXLf+rVuKC6w8DM5VEAG8tVis+esPrJFY2u8WGUWF5R4xRxNwq5Dn/A7cXPk3RYz9j2BfaGq0QzeN6C4DyJb8LHhL7VVJypOAkcnNpmwlmWYmR5FSJxRA2i8Tmx3kVc82eLZgMNoFgStg2gMQHDHkiNw2bOiPt/HWycXPkpmfjJkg/JTe7yEkLDzO4PyvUwnI7HjZT5RUrSCsZeMiU5uZMi0VgQ41ypgCSoF6X3tlCQP3vyCo9HGN9PQIrIerwrEArUHxiZXycDuBKRlyDj85hQdZzNTz7xzQ8IA58wcFrN/o9/LEv5T7W+iSlx4c4rZjHRZ1yqjBTPmXIDCHnVFObGkSkfXYjyYgjc9fRGYLjorTJqk7mVL5U/AVd+rrhFtcnuKI1o0c8rvK/gOPvr6dLYkRVxGhethcHOrIQAV1KSt1HaFyUKqL89t5448gMKHEH4Q+bTjVxyR9Y50WBIvSRgvxmzsXfepnXmoxETlcDo0Yk/rgCn4M2LI1AzW/xY3nlEwbG4SRFLDSWkXPh6Hxq6ftGnf9ZdfMv4lXuSYxPgwvMNjb7GUKkAMU61fay5OdPbU6qnhDjqV+tKOGYvbyOlso+bf8FoyD+tl8eyl2yQtCcpjbdLfYaDtj/ETweS3VKdrDNJ6Eu/l2gGhw44CPkcEE="
  email: false
