---
# tasks file for docker

- name: install docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present

- name: install docker pip packages
  ansible.builtin.pip:
    name: "{{ docker_pip_packages }}"
    state: present

- name: add docker group
  ansible.builtin.group:
    name: docker
    system: yes

- name: start and enable docker
  ansible.builtin.service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
  notify:
    - change group for docker socket
  when:
    - ansible_connection != "docker"
