---
# tasks file for docker

- name: install docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present

- name: install docker pip packages
  ansible.builtin.pip:
    name: "{{ docker_pip_packages }}"
    state: present

- name: create privileged docker user group
  ansible.builtin.group:
    name: docker
    state: present

- name: add privileged users to the docker user group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
  loop: "{{ docker_privileged_users }}"
  loop_control:
    loop_var: user
  when:
    - docker_privileged_users is defined

- name: start and enable docker
  ansible.builtin.service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
  notify:
    - change group for docker socket
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
